### ISSUE TITLE
Mavproxy battery alerts

### ISSUE THREAD

**Issue by J-Lentz** [UAX-Technologies/DeckRC#3]
Mavproxy is announcing battery warning errors because it thinks the battery is at 0%. The battery module can be temporarily unloaded, but this disables all battery alerts. A better solution is to patch Mavproxy to announce specific battery information.

**Comment by ConorMcCaffrey** [comment]
We have removed mavproxy from the standard install. It was mainly used in testing to split up the mavlink steam. It was also used to generate voice feedback to the user before the "underwater voice" problem was fixed with QGC. With that problem fixed we are using QGC to generate voice prompts. The mavproxy prompts are not an issue.

If we add mavproxy back later we should revisit this issue.
